{
 "title": "Generator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU idle",
   "type": "graph",
   "gridPos": { "h": 5, "x": 0, "y": 0, "w": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(averageSeries(collectd.*.cpu*.cpu-idle))"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "graph",
   "gridPos": { "y": 0, "x": 8, "w": 8, "h": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(collectd.*.interface-*[0-9].if_octets.*, '(.if_octets.)|(^.*interface-)', ' ')"
    }
   ]
  },
  {
   "title": "Generators succesful calls",
   "type": "graph",
   "gridPos": { "h": 7, "y": 5, "w": 11, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(maximumAbove(collectd.*.curl*.derive-su*, 0), '((^.*curl-)|(.derive-))', ' ')"
    }
   ]
  },
  {
   "title": "Generators failed calls",
   "type": "graph",
   "gridPos": { "y": 5, "x": 11, "w": 13, "h": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(maximumAbove(collectd.*.curl*.derive-fa*, 0), '((^.*curl-)|(.derive-))', ' ')"
    }
   ]
  }
 ]
}