{
 "title": "SNMP",
 "time": { "from": "now-1h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "CPU_count_1", "label": "CPU_count_1", "query": "1,0.5,0.25,0.125,0.0833" },
   { "name": "CPU_count_2", "label": "CPU_count_2", "query": "1,0.5,0.25,0.125,0.0833" }
  ]
 },
 "panels": [
  {
   "title": "CPU idle",
   "type": "graph",
   "gridPos": { "h": 7, "y": 0, "w": 8, "x": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(collectd.MP[1-2].snmp.cpu-idle_raw, '$CPU_count_1'), 1)"
    },
    {
     "target": "aliasByNode(scale(collectd.MP[3-4].snmp.cpu-idle_raw, '$CPU_count_2'), 1)"
    }
   ]
  },
  {
   "title": "CPU wait",
   "type": "graph",
   "gridPos": { "y": 0, "x": 8, "w": 8, "h": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(collectd.MP[1-2].snmp.cpu-wait_raw, '$CPU_count_1'), 1)"
    },
    {
     "target": "aliasByNode(scale(collectd.MP[3-4].snmp.cpu-wait_raw, '$CPU_count_2'), 1)"
    }
   ]
  },
  {
   "title": "CPU nice",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(collectd.MP[1-2].snmp.cpu-nice_raw, '$CPU_count_1'), 1)"
    },
    {
     "target": "aliasByNode(scale(collectd.MP[3-4].snmp.cpu-nice_raw, '$CPU_count_2'), 1)"
    }
   ]
  },
  {
   "title": "CPU system",
   "type": "graph",
   "gridPos": { "y": 7, "x": 0, "w": 8, "h": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(collectd.MP[1-2].snmp.cpu-system_raw, '$CPU_count_1'), 1)"
    },
    {
     "target": "aliasByNode(scale(collectd.MP[3-4].snmp.cpu-system_raw, '$CPU_count_2'), 1)"
    }
   ]
  },
  {
   "title": "CPU user",
   "type": "graph",
   "gridPos": { "y": 7, "x": 8, "w": 8, "h": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(collectd.MP[1-2].snmp.cpu-user_raw, '$CPU_count_1'), 1)"
    },
    {
     "target": "aliasByNode(scale(collectd.MP[3-4].snmp.cpu-user_raw, '$CPU_count_2'), 1)"
    }
   ]
  },
  {
   "title": "Soft IQR",
   "type": "graph",
   "gridPos": { "h": 7, "y": 7, "w": 8, "x": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.MP[1-2].snmp.irq-soft_irq_raw, 1)"
    },
    {
     "target": "aliasByNode(collectd.MP[3-4].snmp.irq-soft_irq_raw, 1)"
    }
   ]
  }
 ]
}