---
- name: Clone repo
  git:
   repo: 'https://github.com/akibsayyed/safeseven'
   dest: /home/vagrant/safeseven
   clone: yes
  register: safeseven_clonned

- name: Copy files
  template: "src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}"
  with_items:
  - { src: 'roles/ss7/templates/client_config.j2', dest: '/home/vagrant/safeseven/client_config', owner: 'vagrant', group: 'vagrant', mode: '0644'}
  - { src: 'roles/ss7/templates/hlr_config.j2', dest: '/home/vagrant/safeseven/client_config', owner: 'vagrant', group: 'vagrant', mode: '0644'}
  when: safeseven_clonned.changed

...
