---
# Handlers for Grafana stack

- name: restart httpd
  service: name=httpd state=restarted

- name: restart carbon
  service: name=carbon state=restarted

- name: restart grafana
  service: name=grafana-server state=restarted

...
